name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spellcheck:
    name: check spelling
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      
    - uses: actions/setup-go@v4
    - run: curl -L https://git.io/misspell | bash

    - name: Check spelling
      run: ./bin/misspell -error ./src/app/**
  
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install Node.js dependencies
      run: npm ci

    - name: Lint
      run: npm run lint